currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY}

server:
  port: ${PORT:8080}

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/software}

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: currency-converter

  config:
    import: optional:file:.env[.properties]
