currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY:6VZVZCy95XCX8E8C2xcYI2KBDgUGUOE1}

server:
  port: ${PORT:8080}

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/software}

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: currency-converter

  mail:
    host: smtp.gmail.com
    port: 587
    username: proyecto.sis311@gmail.com
    password: '{cipher}493706683ae177777e350f11979e51114ea3ea750c4ee0d3653bd4b9cc6a3718c31e520e18d937d12310d3476d6c0d3c'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: RQ7Fdx7IHKHjbQu8hVDjmKINk8DlLQqp
  realm: software
  resource: backend
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - authRoles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DE ADMINISTRADOR
          patterns:
            - /v1/api/currency/all
          omitted-methods:
            - OPTIONS
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DE USUARIO
          patterns:
            - /v1/api/currency
          omitted-methods:
            - OPTIONS
