currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY:6VZVZCy95XCX8E8C2xcYI2KBDgUGUOE1}

server:
  port: ${PORT:8080}

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/software}

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: currency-converter

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: RQ7Fdx7IHKHjbQu8hVDjmKINk8DlLQqp
  realm: software
  resource: backend
  ssl-required: external
  use-resource-role-mappings: false
  security-constraints:
    - authRoles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DE ADMINISTRADOR
          patterns:
            - /v1/api/currency/all
          omitted-methods:
            - OPTIONS
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DE USUARIO
          patterns:
            - /v1/api/currency
          omitted-methods:
            - OPTIONS
