currency:
  url: ${API_URL:https://api.apilayer.com/exchangerates_data/convert}
  api_key: ${API_KEY:6VZVZCy95XCX8E8C2xcYI2KBDgUGUOE1}

server:
  port: ${PORT:8080}

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.SimpleDataSource
    username: ${USERNAME:postgres}
    password: ${PASSWORD:mysecretpassword}
    url: ${URL:jdbc:postgresql://localhost:5432/software}

  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: currency-converter

  mail:
    host: smtp.gmail.com
    port: 587
    username: proyecto.sis311@gmail.com
    password: efrfzpncmpxjrkrc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  zipkin:
    enabled: true
    base-url: http://localhost:9411
#    discovery-client-enabled: false

  #  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
  rabbitmq:
    host:  sparrow-01.rmq.cloudamqp.com
    port: 5672
    username: itggwiot
    password: FNAc7QotPFaC73UICw8YedtO6GVSspwD
    virtual-host: itggwiot

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#    enabled: false

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8090}
  autodetect-bearer-only: true
  credentials:
    secret: RQ7Fdx7IHKHjbQu8hVDjmKINk8DlLQqp
  realm: software
  resource: backend
  ssl-required: none
  use-resource-role-mappings: false
  security-constraints:
    - authRoles:
        - ADMIN
      security-collections:
        - name: SERVICIOS DE ADMINISTRADOR
          patterns:
            - /v1/api/currency/all
          omitted-methods:
            - OPTIONS
    - auth-roles:
        - USER
      security-collections:
        - name: SERVICIOS DE USUARIO
          patterns:
            - /v1/api/currency
          omitted-methods:
            - OPTIONS
