###
GET http://localhost:8080/v1/api/currency?from=EUR&to=USD&amount=1

### Get all currencies
GET http://localhost:8080/v1/api/currency/all?page=5&size=10&order=desc&orderBy=amount

### Get all currencies by date
GET http://localhost:8080/v1/api/currency/all?dateFrom=2023-02-23&dateTo=2023-02-23&page=0&size=10&order=desc&orderBy=date

### User
GET http://localhost:8080/v1/api/currency/user
Authorization: Basic user user

### Admin
GET http://localhost:8080/v1/api/currency/admin
Authorization: Basic admin admin
