services:
  postgres:
    image: arm64v8/postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: software
    volumes:
      - /Users/chrisalanapazaaguilar/Desktop/SIS-311/docker/postgres:/var/lib/postgresql/data
  currency-converter:
    image: demo:2.0.0
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      URL: ${POSTGRES_URL}
    volumes:
        - /Users/chrisalanapazaaguilar/Desktop/SIS-311/docker/spring:/var/log
    depends_on:
      - postgres


